version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/config/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      docker-dependencies:
        patterns:
          - "*"
