apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cosy-backend
spec:
  # TLS_BLOCK_START
  tls:
    - hosts:
        - DOMAIN_PLACEHOLDER
      secretName: cosy-tls
  # TLS_BLOCK_END
  rules:
    - host: DOMAIN_PLACEHOLDER
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cosy-backend
                port:
                  number: 80
