apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cosy-frontend
  annotations:
    cert-manager.io/cluster-issuer: "cosy-letsencrypt"
spec:
  tls:
    - hosts:
        - DOMAIN_PLACEHOLDER
      secretName: cosy-tls
  rules:
    - host: DOMAIN_PLACEHOLDER
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cosy-frontend
                port:
                  number: 80
